version: '3'

services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:6.5.4
    hostname: jetea-filebeat
    restart: always
    network_mode: host
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ${SITE_DIR}:/www:ro
