name: mm

filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /www/monitor/storage/logs/*.log
    encoding: utf-8
    scan_frequency: 10s
    backoff: 1s
    close_inactive: 30m
    json.add_error_key: true
    clean_removed: true
    ignore_older: 24h
    clean_inactive: 25h
    tags: ["filebeat", "lumen_log", "mm"]
    fields:
      list: "lumen_log_list"
    multiline.pattern: ^\[\d{4}
    multiline.negate: true
    multiline.match: after
    tail_files: true #文件末尾开始读取

# output.redis:
#   hosts: ["192.168.3.92:6380"]
#   timeout: 5
#   key: "%{[fields.list]:lumen_log_list}"
#   datatype: "list"

# output.logstash:
#   hosts: ["172.24.14.181:5044"]

output.kafka:
  hosts: ["kafka.log.com:9092"]
  topic: 'log'
  partition.round_robin:
    reachable_only: false
  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000
