version: "3"

services:
    elasticsearch:
        image: docker-elasticsearch
        build:
            context: elasticsearch/
            dockerfile: Dockerfile
            args:
                - ELK_VERSION=${ELK_VERSION}
        restart: always
        environment:
            - cluster.name=es01
            - bootstrap.memory_lock=true
            - discovery.type=single-node
            - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - xpack.security.enabled=false
            - xpack.monitoring.enabled=false
            - xpack.graph.enabled=false
            - xpack.watcher.enabled=false
            - xpack.ml.enabled=false
        volumes:
            - ./runtime/elasticsearch/data:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
            - 9300:9300
    # 说明:
    # port: 5044 filebeat 默认端口
    #       9600 http 端口
    logstash:
        image: docker-logstash
        build:
            context: logstash/
            args:
                - ELK_VERSION=${ELK_VERSION}
        restart: always
        volumes:
            - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
            - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
        environment:
            - "LS_JAVA_OPTS=-Xms512m -Xmx512m"
        depends_on:
            - elasticsearch

    kibana:
        image: docker-kibana
        build:
            context: kibana/
            args:
                - ELK_VERSION=${ELK_VERSION}
        restart: always
        volumes:
            - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
        ports:
            - 5601:5601
        environment:
            - elasticsearch.username=elastic
            - elasticsearch.password=${ELASTIC_PASSWORD}
        depends_on:
            - elasticsearch

    # 说明:
    # port: 6379
    # conf: /usr/local/etc/redis/redis.conf
    redis:
        image: redis:4.0-stretch
        restart: always
        ports:
            - 6380:6379
        volumes:
            - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
