version: '3'

services:
  # 说明:
  # port: 6379
  # conf: /usr/local/etc/redis/redis.conf
  redis:
    image: redis:4.0-stretch
    restart: always
    ports:
      - 6380:6379
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
